args <- commandArgs(trailingOnly=TRUE)
library(Rwave, lib.loc="C:/Users/Hila/Documents/R/win-library/3.3")
wgbs_smooth_vector <- read.delim(args[1], header=FALSE, col.names=c("val"))
irys_vector <- read.delim(args[2], header=FALSE, col.names=c("val"))
wgbs_cwt_dog <- DOG(wgbs_smooth_vector$val, noctave=1, moments=1, plot=FALSE)
wgbs_cwg_dog_abs <- abs(wgbs_cwt_dog)
irys_cwt_dog <- DOG(irys_vector$val, noctave=1, moments=1, plot=FALSE)
irys_cwg_dog_abs <- abs(irys_cwt_dog)
write.table(wgbs_cwg_dog_abs, file=args[3], quote=FALSE, sep="\t", row.names = FALSE, col.names = FALSE)
write.table(irys_cwg_dog_abs, file=args[4], quote=FALSE, sep="\t", row.names = FALSE, col.names = FALSE)